config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dreams
  resources :main_profiles
  resources :items do
    resources :sub_purchased_logs
  end
  root to:"dreams#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :sub_purchased_logs,  dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :sub_purchased_logs,  dependent: :destroy
  has_one_attached :item_image,  dependent: :destroy
  validates :item_name, presence: true
  validates :price, presence: true
end

app/models/main_profile.rb
class MainProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  
  with_options presence: true do
    validates :user_name
    validates :dead_line
    validates :mission
  end
end

app/models/sub_purchased_log.rb
class SubPurchasedLog < ApplicationRecord
  attr_accessor :token
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :where
  belongs_to :area

  belongs_to :item

  with_options presence: true do
    validates :quantitiy
    validates :price
    validates :purchased_name
    validates :postal_code
    validates :city
    validates :address
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :password
  end
  has_one :main_profile,  dependent: :destroy
  has_many :items,  dependent: :destroy
end

app/models/where.rb
class Where < ActiveHash::Base
  self.data = [
    { id: 1, name: '特になし' },
    { id: 2, name: 'Twitterで知った' },
    { id: 3, name: 'Facebookで知った' },
    { id: 4, name: 'Instagramで知った' }
  ]

  include ActiveHash::Associations
  has_many :sub_purchased_logs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    main_profile = MainProfile.includes(:user)
    if user_signed_in?
      @other_dreams = main_profile.where.not(user_id: current_user.id)
    else
      @other_dreams = main_profile
    end
  end
  def show
    @user = User.find(params[:id])
    @main_profile = MainProfile.where(user_id: @user.id).first
    item = Item.includes(:user)
    @item = item.where(user_id: @user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :item_set, except: [:new, :create]
  
  def new
    @item=Item.new
  end
  def create
    @item=Item.new(params_item)
    if @item.save
      redirect_to dream_path(current_user.id)
    else
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @item.update(params_item)
      redirect_to dream_path(current_user.id)
    else
      render :edit
    end
  end
  def destroy
    @item.destroy
    redirect_to dream_path(current_user.id)
  end

  private

  def params_item
    params.require(:item).permit(:item_image, :item_name, :explanation, :price).merge(user_id: current_user.id)
  end
  def item_set
    @item = Item.find(params[:id])
  end
  
end

app/controllers/main_profiles_controller.rb
class MainProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index_new, only: [:new, :create]
  def new
    @main_profile = MainProfile.new
  end
  def create
    @main_profile = MainProfile.new(params_main_profile)
    if @main_profile.save
      redirect_to dream_path(current_user.id)
    else
      render :new
    end
  end
  def edit
    @main_profile = MainProfile.where(user_id: current_user.id).first
  end
  def update
    @main_profile = MainProfile.where(user_id: current_user.id).first
    if @main_profile.update(params_main_profile)
      redirect_to dream_path(current_user.id)
    else
      render :edit
    end
  end
  private
  def params_main_profile
    params.require(:main_profile).permit(:user_name, :user_profile, :image, :mission, :mission_ex, :URL_twitter, :URL_facebook, :URL_instagram, :dead_line).merge(user_id: current_user.id)
  end
  def move_to_index_new
    if MainProfile.exists?(user_id: current_user.id)
      redirect_to root_path
    end
  end
end

app/controllers/sub_purchased_logs_controller.rb
class SubPurchasedLogsController < ApplicationController
  def index
  end
  def new
    @item = Item.find(params[:item_id])
    @sub_purchased_log = SubPurchasedLog.new
  end
  def create
    @item = Item.find(params[:item_id])
    @sub_purchased_log = SubPurchasedLog.new(params_sub_purchased_log)
    if @sub_purchased_log.valid?
      payjp
      @sub_purchased_log.save
      redirect_to item_sub_purchased_logs_path(params[:item_id])
    else
      render :new
    end
  end

  private

  def params_sub_purchased_log
    params.require(:sub_purchased_log).permit(:quantitiy, :price, :purchased_name, :postal_code, :area_id, :city, :address, :where_id).merge(item_id: params[:item_id], token: params[:token])
  end 
  
  def payjp
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: @sub_purchased_log.price, 
      card: params_sub_purchased_log[:token],    
      currency: 'jpy'              
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_profiles_helper.rb
module MainProfilesHelper
end

app/helpers/sub_purchased_logs_helper.rb
module SubPurchasedLogsHelper
end

app/views/dreams/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="app-explanation">
    <div class="concept">
    <h1 class="concept-message">SNSの中継地点となるアプリ</h1>
    </div>
    <div class="contents">
      <div class="conceptcontent">
        <%= image_tag "コミュニケーションアイコン3.png", class: "concept-icon" %> 
        <p class ="conceptmessage">SNSでファンを獲得しよう</p>
      </div>
      <div class="conceptcontent">
        <%= image_tag "icon_121140_256.png", class: "concept-icon" %> 
        <p class ="conceptmessage">様々なSNSでファンと繋がろう</p>
      </div>
      <div class="conceptcontent">
        <%= image_tag "wowata.png", class: "concept-icon" %> 
        <p class ="conceptmessage">ファンとより強固な関係を築こう</p>
      </div>
    </div>
    <div class="messagecontent">
     <h1 class="message">さぁ、ファンと繋がろう</h1>
    </div>
  </div>
  <div class="others-dreams">
    <div class="concept">
    <h1 class="concept-message">他の人を見る</h1>
    </div>
    <div class="others-dreams-content">
      <%if @other_dreams.present?%>
        <%@other_dreams.each do |other_dream|%>
          <div class=others-dream>
            <%= link_to dream_path(other_dream.user_id), id:"contents" do%>
            <%if other_dream.image.present?%>
              <%=image_tag other_dream.image, class:"user-icon"%>
            <%else%>
              <%=image_tag "gal_o_man.png", class:"user-icon"%>
            <%end%>
              <h1 class="user-contents" ><%=other_dream.user_name%></h1>
              <h1 class="user-contents">「<%= other_dream.mission%>」</h1>
            <%end%>
          </div>
        <%end%>
      <%end%>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/dreams/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <%if @user.main_profile.present?%>
    <div class="profilecontents">
      <div class="profiles">
        <div class="userprofiles">
          <div class="userimage">
          <%if @main_profile.image.present?%>
          <%= image_tag @main_profile.image, class:"userimagecontent"%>
          <%else%>
          <%=image_tag "gal_o_man.png" ,class:"userimagecontent"%>
          <%end%>
          </div>
          <div class="username">
          <h1 class="usernamecontent"><%=@main_profile.user_name%></h1>
          </div>
          <div class="uesrexplanation">
          <p class="uesrexplanationcontent"><%=@main_profile.user_profile%></p>
          </div>
        </div>
        <div class="usermissions">
          <div class="usermission">
          <h1 class="usermissioncontent"><%= @main_profile.mission%></h1>
          </div>
          <div class="usermissionexplanation">
          <p class="usermissionexplanationcontent"><%= @main_profile.mission_ex %> </p>
          </div>
        </div>
      </div>
      <div class="SNSurls">
        <div class="URLs">
          <%if @main_profile.URL_facebook.present?%>
            <%= link_to "#{@main_profile.URL_facebook}" ,id:"URLfacebook" do %>
            <%=image_tag "icon_017870_256.png" ,class:"icon"%>
            facebook
            <%end%>
          <%else%>
            <a href="#" id="URLfacebooknone"><%=image_tag "icon_017870_256.png" ,class:"icon"%>facebook</a>
          <%end%>
        </div>
        <div class="URLs">
          <%if @main_profile.URL_twitter.present?%>
            <%= link_to "#{@main_profile.URL_twitter}" ,id:"URLtwitter" do %>
            <%=image_tag "icon_017890_256.png" ,class:"icon"%>
            twitter
            <%end%>
          <%else%>
            <a href="#" id="URLtwitternone"><%=image_tag "icon_017890_256.png" ,class:"icon"%>twitter</a>
          <%end%>
        </div>
        <div class="URLs">
          <%if @main_profile.URL_instagram.present?%>
            <%= link_to "#{@main_profile.URL_instagram}" ,id:"URLinstagram" do %>
            <%=image_tag "icon_062470_256.png" ,class:"icon"%>
            instagram
            <%end%>
          <%else%>
          <a href="#" id="URLinstagramnone"><%=image_tag "icon_062470_256.png" ,class:"icon"%>instagram</a>
          <%end%>
        </div>
      </div>
    </div>
    <div class="limit-contents">
      <h1 class="limit-mes">目標達成期限まで</h1>
      <h1 class="limit-time" id="limit-time"><%=@main_profile.dead_line %></h1>
    </div>
  <%else%>
    <div class="profilecontents">
      <div class="profiles">
        <div class="userprofiles">
          <div class="userimage">
          <%=image_tag "gal_o_man.png" ,class:"userimagecontent"%>
          </div>
          <div class="username">
          <h1 class="usernamecontent">名前を決めよう </h1>
          </div>
          <div class="uesrexplanation">
          <p class="uesrexplanationcontent">自分のプロフィールを書こう</p>
          </div>
        </div>
        <div class="usermissions">
          <div class="usermission">
          <h1 class="usermissioncontent">目標を決めよう</h1>
          </div>
          <div class="usermissionexplanation">
          <p class="usermissionexplanationcontent">目標の説明</p>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <div class="useritem">
    <h1 class="useritemtitle">商品</h1>
    <div class="useritemcontents">
    <%if @item.present?%>
      <% @item.each do |item|%>
        <%=link_to item_path(item.id) ,id:"useritemcontentURL" do %>
          <div class="useritemcontent">
            <div class="useritemcontentimage">
              <%=image_tag item.item_image ,class:"userimagecontent"%>
            </div>
            <h1 class="useritemcontenttitle"><%= item.item_name%></h1>
          </div>
        <%end%>
      <%end%>
    <%else%>
    <h1 class="itemmes">商品を追加しよう！！</h1>
    <%end%>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/items/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: @item, class:"form", local: true do |f|%>
    <h1 class="formmaintitle">支援要項追加</h1>
    <div class="formcontens">
      <p class="formtitle">画像</p>
      <%= f.file_field :item_image, class:"fileformname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">名前<span class="indispensable">*必須</span></p>
      <%= f.text_field :item_name, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">説明</p>
      <%= f.text_area :explanation, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">価格<span class="indispensable">*必須</span></p>
      <%= f.text_field :price, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <%= f.submit "作成する" ,class:"submitbtn"%>
    </div>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: @item, class:"form", local: true do |f|%>
    <h1 class="formmaintitle">支援要項追加</h1>
    <div class="formcontens">
      <p class="formtitle">画像</p>
      <%= f.file_field :item_image, class:"fileformname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">名前<span class="indispensable">*必須</span></p>
      <%= f.text_field :item_name, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">説明</p>
      <%= f.text_area :explanation, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">価格<span class="indispensable">*必須</span></p>
      <%= f.text_field :price, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <%= f.submit "作成する" ,class:"submitbtn"%>
    </div>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>
  <div class="main">
    <div class="itemexplanations">
      <div class="itemimage">
        <%=image_tag @item.item_image, class:"itemimageshow"%>
      </div>
      <div class="itemexplanation">
        <div class="itemname">
          <h1><%= @item.item_name %></h1>
        </div>
        <div class="itemprice">
        <h1>「<%=@item.price%>円」</h1>
        </div>
        <%if @item.explanation.present?%>
        <div class="itemexplanationshow">
          <p><%=@item.explanation%></p>
        </div>
        <%end%>
      </div>
    </div>
    <%if @item.user_id == current_user.id%>
      <div class="purchsedbtn">
        <%=link_to "編集する",edit_item_path(@item.id),id:"purchsedbtn"%>
      </div>
      <div class="purchsedbtn">
        <%=link_to "削除する",item_path(@item.id), method: :delete ,id:"purchsedbtn"%>
      </div>
    <%else%>
      <div class="purchsedbtn">
        <%=link_to "購入する",new_item_sub_purchased_log_path(@item.id),id:"purchsedbtn"%>
      </div>
    <%end%>
  </div>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_profiles/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: @main_profile, class:"form", local: true do |f|%>
    <h1 class="formmaintitle">プロフィー設定</h1>
    <div class="formcontens">
      <p class="formtitle">画像</p>
      <%= f.file_field :image, class:"fileformname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">名前<span class="indispensable">*必須</span></p>
      <%= f.text_field :user_name, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">プロフィール</p>
      <%= f.text_area :user_profile, class:"formname"%>
    </div>
    <div class="formcontens">
      <p class="formtitle">ミッション<span class="indispensable">*必須</span></p>
      <%= f.text_field :mission, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">ミッションの説明</p>
      <%= f.text_area :mission_ex, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">目標達成期限<br><span class="indispensable">*必須</span><span>(右のアイコンをクリック)</span></p>
      <%= f.datetime_field :dead_line, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">twitter（URL）</p>
      <%= f.text_field :URL_twitter, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">facebook（URL）</p>
      <%= f.text_field :URL_facebook, class:"formname"%>
    </div>
    <div class="formcontens">
      <p class="formtitle">instagram（URL）</p>
      <%= f.text_field :URL_instagram, class:"formname" %>
    </div>
    <div class="formcontens">
      <%= f.submit "登録する" ,class:"submitbtn"%>
    </div>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/main_profiles/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: @main_profile, class:"form", local: true do |f|%>
    <h1 class="formmaintitle">プロフィー設定</h1>
    <div class="formcontens">
      <p class="formtitle">画像</p>
      <%= f.file_field :image, class:"fileformname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">名前<span class="indispensable">*必須</span></p>
      <%= f.text_field :user_name, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">プロフィール</p>
      <%= f.text_area :user_profile, class:"formname"%>
    </div>
    <div class="formcontens">
      <p class="formtitle">ミッション<span class="indispensable">*必須</span></p>
      <%= f.text_field :mission, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">ミッションの説明</p>
      <%= f.text_area :mission_ex, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">目標達成期限<br><span class="indispensable">*必須</span><span>(右のアイコンをクリック)</span></p>
      <%= f.datetime_field :dead_line, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">twitter（URL）</p>
      <%= f.text_field :URL_twitter, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">facebook（URL）</p>
      <%= f.text_field :URL_facebook, class:"formname"%>
    </div>
    <div class="formcontens">
      <p class="formtitle">instagram（URL）</p>
      <%= f.text_field :URL_instagram, class:"formname" %>
    </div>
    <div class="formcontens">
      <%= f.submit "登録する" ,class:"submitbtn"%>
    </div>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="footertext">--footer--</p>
</div>

app/views/shared/_header.html.erb
<div class="header">
<div id="fadeLayer" class="hidden"></div>
  <div class="title">
    <%= link_to "DREAM", root_path, class:"title-content" %>
  </div>
  <% if user_signed_in? %>
    <div class ="nenucontents">
    <%=image_tag "sozai_cman_jp_20210826135329.png", id:"menuicon"%>
    <ul class="menuber hidden" id="menuber">
      <li id="list1" class="lists"><%=link_to "マイページ", dream_path(current_user.id), id:"lists_path"%></li>
      <%if current_user.main_profile.present?%>
      <li id="list2" class="lists"><%=link_to "プロフィール編集", edit_main_profile_path(current_user.id), id:"lists_path"%></li>
      <%else%>
      <li id="list5" class="lists"><%=link_to "プロフィール作成", new_main_profile_path, id:"lists_path"%></li>
      <%end%>
      <li id="list3" class="lists"><%=link_to "商品追加", new_item_path, id:"lists_path"%></li>
      <li id="list4" class="lists"><%=link_to "ログアウト", destroy_user_session_path, method: :delete ,id:"lists_path"%> </li>
    </ul>
    </div>
    <%else%>
    <div class="user-function">
      <div class="user-functions">
        <%=link_to "ログイン", new_user_session_path, class:"user-content" %> 
      </div>
      <div class="user-functions">
        <%=link_to "新規登録", new_user_registration_path, class:"user-content" %>
      </div>
    <%end%>
  </div>
</div>

app/views/sub_purchased_logs/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="thx_contents">
    <h1 class="thx_mes">支援感謝です!!</h1>
    <%=link_to "ホームに戻る", root_path,id:"thx_back" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/sub_purchased_logs/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="itemexplanations">
    <div class="itemimage">
      <%=image_tag @item.item_image, class:"itemimageshow"%>
    </div>
    <div class="itemexplanation">
      <div class="itemname">
        <h1><%= @item.item_name %></h1>
      </div>
      <div class="itemprice">
      <h1>「<span id="itemprice"><%=@item.price%></span>円」</h1>
      </div>
      <div class="priceclac">
      <form>
        <input type="text" class="priceclacform" id="itemcount">個（半角数字）
      </form>
        <h1><span id="calc-price">~~~~~</span>円</h1>
        </div>
    </div>
  </div>
  <%=form_with model: [@item,@sub_purchased_log], class:"form", id:"charge-form", local: true do |f|%>
    <h1 class="formmaintitle">情報記入</h1> 
    <div class="formcontens">
      <%= f.text_field :quantitiy, class:"formname hidden",id:"itemquantitiy" %>
    </div>
    <div class="formcontens">
      <%= f.text_field :price, class:"formname hidden", id:"item-price"%>
    </div>
        <%# カード情報の入力 %>
    <div class='formcontens'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :card_number, class:"formname", id:"card-number", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_field :card_exp_month, class:"input-expiration-date", id:"card-exp-month" %>
          <p class="input-expiration-date-p">月</p>
          /20<%= f.text_field :card_exp_year, class:"input-expiration-date", id:"card-exp-year"%>
          <p class="input-expiration-date-p">年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :card_cvc, class:"input-expiration-date", id:"card-cvc", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>

    <div class="formcontens">
      <h1 class='info-input-haedline'>
        お客様情報入力
      </h1>
      <p class="formtitle">お名前<span class="indispensable">*必須</span></p>
      <%= f.text_field :purchased_name, class:"formname" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">郵便番号<span class="indispensable">*必須</span></p>
      <%= f.text_field :postal_code, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">都道府県<span class="indispensable">*必須</span></p>
      <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box"}) %>
    </div>
    <div class="formcontens">
      <p class="formtitle">市町村<span class="indispensable">*必須</span></p>
      <%= f.text_field :city, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">住所<span class="indispensable">*必須</span></p>
      <%= f.text_field :address, class:"formname", maxlength:"20" %>
    </div>
    <div class="formcontens">
      <p class="formtitle">どこで知りましたか？</p>
      <%= f.collection_select(:where_id, Where.all, :id, :name, {}, {class:"select-box"}) %>
    </div>
    <div class="formcontens" id="purchased_btn">
      購入する
    </div>
  </div>
  <div class="purchased_con hidden" id ="purchased_mes">
    <h1 class="purchased_mes1">本当に購入しますか？</h1>
    <h1 class="purchased_mes2">「<%= @item.item_name %>」 × <span id="item_count_con"></span>個 = <span id="item_price_con"></span>円</h1>
    <%= f.submit "購入する" ,class:"purchased_con_btn", id:"button"%>
  </div>
  <%end%>
<%= render "shared/footer" %>